name: Run td-bot-v1

on:
  schedule:
    - cron: "25 8 * * 1-5"

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run script
        uses: docker://python:3
        with:
          entrypoint: python
          args: options7.py
  stop-bot:
    runs-on: ubuntu-latest
    needs: run-bot
    if: always()
    steps:
      - name: Stop script
        run: pkill -f options7.py
        shell: bash
    - name: Send notification
        if: always()
        run: echo "td-bot-v1 has been stopped." | mail -s "td-bot-v1 stopped" rryanhermes@gmail.com
