name: Run td-bot-v1

on:
  schedule:
    - cron: "25 8 * * 1-5"
    - cron: "5 15 * * 1-5"

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run script
        run: |
          python options7.py &
      - name: Notify start
        uses: dawidd6/action-send-mail@v2.1.0
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "TD Bot started"
          to: rryanhermes@gmail.com
          body: "TD Bot has started."

  stop-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Stop bot
        run: |
          sudo pkill -f "python options7.py"
      - name: Notify stop
        uses: dawidd6/action-send-mail@v2.1.0
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "TD Bot stopped"
          to: rryanhermes@gmail.com
          body: "TD Bot has stopped."
